### ISSUE TITLE
final steps

### ISSUE THREAD

**Issue by timm** [ai-se/cocreport#40]
1) please proof my replies to reviewers

2) please check whole document for any reference to MRE

3) please check that the text describing the figures DOES actual describe the figures. i've found and removed a few "ghosts" that discuss features of the figures that are now no longer present. i think i've catched the, all but you never can tell

4) i need to write a letter to the editor. still working on that

**Comment by bigfatnoob** [comment]
1) Yeah. Seems good. Corrected few typos.
2) There was a reference in python code in fig 7. Removed it now.
3) There was one more ghost fig. Removed it.

**Comment by timm** [comment]
are we done now? nothing from our co-authors? any typos in my replies to reviewers? 

what was the ghost you removed?

**Comment by bigfatnoob** [comment]
Nothing from the co authors.
I could fixed any typos in ur replies on Saturday. Don't think there are any if you haven't made changes since then.
There was results chart showing error results using e^2. We had used it to show that using any error measure would not change our conclusions. I think you removed the text but forgot to drop the image. This detail was in BLUE.

**Comment by yy2111** [comment]
Tim/George,

Can either of you send out the latest PDF? 

Thanks,

Ye
